config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'home#index'
  get 'sobre', to: 'home#sobre'
  get 'noticias', to: 'home#noticias'
  get 'noticia_view/:id', to: 'home#noticia_view'
  get 'galerias', to: 'home#galerias'
  get 'galeria_view/:id', to: 'home#galeria_view'
  get 'videos', to: 'home#videos'
  get 'contato', to: 'home#contato'
  post 'send_contato', to: 'home#send_contato'

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up'}

  namespace :adm do
    get 'dashboard', to: 'dashboard#index'
    get 'galerias/imagem_capa/:id', to: 'galerias#imagem_capa'
    resources :banners
    resources :noticias
    resources :videos
    resources :galerias
    resources :galerias_imagens
  end

  namespace :auth do
    resources :roles
  end

  root 'home#index'

end

app/models/adm.rb
module Adm
  def self.table_name_prefix
    'adm_'
  end
end

app/models/adm/galeria.rb
class Adm::Galeria < ActiveRecord::Base
  #o relacionamento tem que colocar o nome do model e não o nome da tabelas
  #no  has_many tem que ser o nome model no plural has_many  :galerias_imagens
  #no  belongs_to  tem que ser o nome model no singular belongs_to :galeria
  has_many    :galerias_imagens, :inverse_of => :galeria, :dependent => :destroy
  # enable nested attributes for galerias_imagens through galeria class
  accepts_nested_attributes_for :galerias_imagens, allow_destroy: true
end

app/models/adm/galerias_imagem.rb
class Adm::GaleriasImagem < ActiveRecord::Base
  belongs_to  :galeria, :polymorphic => true
  #validates   :galeria, presence: true
  # GaleriasImagem uploader using carrierwave
  mount_uploader :imagem, GaleriaImagemUploader
end

app/models/adm/noticia.rb
class Adm::Noticia < ActiveRecord::Base
  mount_uploader :imagem_capa, NoticiaUploader # Tells rails to use this uploader for this model.
  
  validates :titulo, presence: true # Make sure the owner's name is present.
  validates :subtitulo,  presence: true # Make sure the owner's name is present.
  validates :descricao, presence: true # Make sure the owner's name is present.

end

app/models/adm/video.rb
class Adm::Video < ActiveRecord::Base
  validates :titulo, :url_codigo, presence: true
  before_validation(on: [ :create, :update ]) do
    self.url_codigo = parse_youtube(url_codigo) #url_codigo = params[:adm_video][:url_codigo]
  end

  private
  #  pega só o codigo do link youtube para inserir no banco 
  def parse_youtube(url)
   if !url.blank?
     regex = /(?:.be\/|\/watch\?v=|\/(?=p\/))([\w\/\-]+)/
     return url.match(regex)[1]
   end
 end

end

app/controllers/adm/banners_controller.rb
class Adm::BannersController < ApplicationController
  # before_action :require_authentication
  #devise autheticação
  before_action :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource #metodo cancancan
  layout "adm_layout"
  before_action :set_adm_banner, only: [:show, :edit, :update, :destroy]

  # GET /adm/banners
  # GET /adm/banners.json
  def index
    @adm_banners = Adm::Banner.all
  end

  # GET /adm/banners/1
  # GET /adm/banners/1.json
  def show
  end

  # GET /adm/banners/new
  def new
    @adm_banner = Adm::Banner.new
  end

  # GET /adm/banners/1/edit
  def edit
  end

  # POST /adm/banners
  # POST /adm/banners.json
  def create
    @adm_banner = Adm::Banner.new(adm_banner_params)

    respond_to do |format|    

      if @adm_banner.save
        # if !params[:adm_banner][:imagem].blank?
        #   path ='img_banners'
        #   @adm_banner[:imagem] = upload_file(path,params[:adm_banner][:imagem])
        # end
        format.html { redirect_to @adm_banner, notice: t('banners.create_success') }
        format.json { render :show, status: :created, location: @adm_banner }
      else
        format.html { render :new }
        format.json { render json: @adm_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adm/banners/1
  # PATCH/PUT /adm/banners/1.json
  def update
    # if !params[:adm_banner][:imagem].blank?
    #   path ='img_banners'
    #   adm_banner_params[:imagem] = upload_file(path,params[:adm_banner][:imagem])
    # end  
    respond_to do |format| 
      if @adm_banner.update(adm_banner_params)
        format.html { redirect_to @adm_banner, notice: t('banners.update_success') }
        format.json { render :show, status: :ok, location: @adm_banner }
      else
        format.html { render :edit }
        format.json { render json: @adm_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adm/banners/1
  # DELETE /adm/banners/1.json
  def destroy
    File.delete(Rails.root.join('public', 'img_banners',@adm_banner.imagem))
    @adm_banner.destroy

    respond_to do |format|
      format.html { redirect_to adm_banners_url, notice: t('banners.destroy_success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adm_banner
      @adm_banner = Adm::Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adm_banner_params
      params.require(:adm_banner).permit(:titulo, :imagem, :link)
    end

    def upload_file(path, param )
     uploaded_io = param
     if !File::directory?( Rails.root.join('public',path) )
      Dir.mkdir( Rails.root.join('public',path), 777)
    end
    File.open(Rails.root.join('public',path, sanitize_filename(uploaded_io.original_filename)), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    return sanitize_filename(uploaded_io.original_filename)
  end

  def sanitize_filename(file_name)
  # get only the filename, not the whole path (from IE)
  just_filename = File.basename(file_name)
  # replace all none alphanumeric, underscore or perioids with underscore
  just_filename.gsub(/[^\w\.\_]/,'_')
end
end

app/controllers/adm/dashboard_controller.rb
class Adm::DashboardController < ApplicationController
  # before_action :require_authentication
  #devise autheticação
  before_action :authenticate_user!
  layout "adm_layout"
  def index
  end
end

app/controllers/adm/galerias_controller.rb
class Adm::GaleriasController < ApplicationController
  # before_action :require_authentication
  before_action :authenticate_user! #devise autheticação
  load_and_authorize_resource #metodo cancancan
  layout "adm_layout"
  before_action :set_adm_galeria, only: [:show, :edit, :update, :destroy, :imagem_capa]
  
  # GET /adm/galerias
  # GET /adm/galerias.json
  def index
    @adm_galerias = Adm::Galeria.all
  end

  # GET /adm/galerias/1
  # GET /adm/galerias/1.json
  def show
    @adm_galerias_imagem = Adm::Galeria.find(params[:id]).galerias_imagens.all
  end

  # GET /adm/galerias/new
  def new
    @adm_galeria = Adm::Galeria.new
  end

  # GET /adm/galerias/1/edit
  def edit
  end

  # POST /adm/galerias
  # POST /adm/galerias.json
  def create
    @adm_galeria = Adm::Galeria.new(adm_galeria_params)
    respond_to do |format|
      if @adm_galeria.save       
         # to handle multiple images upload on create
         if params[:adm_galeria][:imagem]
          params[:adm_galeria][:imagem].each { |image|
            @adm_galeria.galerias_imagens.create(imagem: image)
          }
        end
        format.html { redirect_to @adm_galeria, notice: t('galerias.create_success') }
        format.json { render :show, status: :created, location: @adm_galeria }
      else
        format.html { render :new }
        format.json { render json: @adm_galeria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adm/galerias/1
  # PATCH/PUT /adm/galerias/1.json
  def update
    respond_to do |format|
      if @adm_galeria.update(adm_galeria_params)
           # to handle multiple images upload on create
           if params[:adm_galeria][:imagem]
            params[:adm_galeria][:imagem].each { |image|
              @adm_galeria.galerias_imagens.create(imagem: image)
            }
          end
          format.html { redirect_to @adm_galeria, notice: t('galerias.update_success') }
          format.json { render :show, status: :ok, location: @adm_galeria }
        else
          format.html { render :edit }
          format.json { render json: @adm_galeria.errors, status: :unprocessable_entity }
        end
      end
    end

  # DELETE /adm/galerias/1
  # DELETE /adm/galerias/1.json
  def destroy
    @adm_galeria.destroy
    respond_to do |format|
      format.html { redirect_to adm_galerias_url, notice: t('galerias.destroy_success') }
      format.json { head :no_content }
    end
  end

#PATCH/PUT /adm/imagem_capa/1
def imagem_capa
  if @adm_galeria.update(imagem_capa: params[:imagem_capa])
    respond_to do |format|
      format.html { redirect_to adm_galerias_url, notice: t('galerias.imagem_capa_success') }
      format.json { head :no_content }
    end
  end
end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_adm_galeria
      @adm_galeria = Adm::Galeria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adm_galeria_params
      params.require(:adm_galeria).permit(:titulo, :descricao, :imagem_capa)
    end
  end

app/controllers/adm/galerias_imagens_controller.rb
class Adm::GaleriasImagensController < ApplicationController
  # before_action :require_authentication
  before_action :authenticate_user! #devise autheticação
  load_and_authorize_resource #metodo cancancan
  layout "adm_layout"
  before_action :set_adm_galerias_imagem, only: [:show, :edit, :update, :destroy]

  # GET /adm/galerias_imagens
  # GET /adm/galerias_imagens.json
  def index
    @adm_galerias_imagens = Adm::GaleriasImagem.all
  end

  # GET /adm/galerias_imagens/1
  # GET /adm/galerias_imagens/1.json
  def show
	 #@adm_galeria = Adm::Galeria
	@adm_galerias_imagem =Adm::Galeria.find(params[:id]).galerias_imagens.all # @adm_galeria.preload(:galerias_imagens) #joins(:galerias_imagens) 
	#@adm_galeria = Adm::Galeria.find(params[:id]).galerias_imagens.all
	#abort('gil');
  end

  # GET /adm/galerias_imagens/new
  def new
    @adm_galerias_imagem = Adm::GaleriasImagem.new 
  end

  # GET /adm/galerias_imagens/1/edit
  def edit
  end

  # POST /adm/galerias_imagens
  # POST /adm/galerias_imagens.json
  def create   
	@adm_galerias_imagem = Adm::GaleriasImagem.new(adm_galerias_imagem_params)
      if @adm_galerias_imagem.save  
        head :created     
      else
		head :bad_request      
      end
  end

  # PATCH/PUT /adm/galerias_imagens/1
  # PATCH/PUT /adm/galerias_imagens/1.json
  def update   
      if @adm_galerias_imagem.update(adm_galerias_imagem_params)
		head :created      
      else
		head :bad_request
      end 
  end

# truncated for brevity.
  #def create
  #  @adm_galerias_imagem = Adm::GaleriasImagem.new(adm_galerias_imagem_params)
  #  @adm_galerias_imagem.save
  #end

  # DELETE /adm/galerias_imagens/1
  # DELETE /adm/galerias_imagens/1.json
  def destroy
    @adm_galerias_imagem.destroy
    respond_to do |format|
      format.html { redirect_to adm_galerias_imagens_url, notice: 'Galerias imagem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adm_galerias_imagem
      @adm_galerias_imagem = Adm::GaleriasImagem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adm_galerias_imagem_params
      params.require(:adm_galerias_imagem).permit(:galeria_id, :imagem)
    end
  end

app/controllers/adm/noticias_controller.rb
class Adm::NoticiasController < ApplicationController
  # before_action :require_authentication
  before_action :authenticate_user! #devise autheticação
  load_and_authorize_resource #metodo cancancan
  layout "adm_layout"
  before_action :set_adm_noticia, only: [:show, :edit, :update, :destroy]

  # before_action :login_required, except: [:index, :show]
  # before_action :role_required,  except: [:index, :show]

  # before_action :set_page,       only: [:edit, :update, :destroy]
  # before_action :owner_required, only: [:edit, :update, :destroy]

  # GET /adm/noticias
  # GET /adm/noticias.json
  def index   
    @adm_noticias = Adm::Noticia.all
  end

  # GET /adm/noticias/1
  # GET /adm/noticias/1.json
  def show
  end

  # GET /adm/noticias/new
  def new
    @adm_noticia = Adm::Noticia.new
  end

  # GET /adm/noticias/1/edit
  def edit
  end

  # POST /adm/noticias
  # POST /adm/noticias.json
  def create
    @adm_noticia = Adm::Noticia.new(adm_noticia_params)

    respond_to do |format|
    # adm_noticia_upload(params[:adm_noticia][:imagem_capa])
    if @adm_noticia.save
      format.html { redirect_to @adm_noticia, notice: t('noticias.create_success') }
      format.json { render :show, status: :created, location: @adm_noticia }
    else
      format.html { render :new }
      format.json { render json: @adm_noticia.errors, status: :unprocessable_entity }
    end
  end
end

  # PATCH/PUT /adm/noticias/1
  # PATCH/PUT /adm/noticias/1.json
  def update
    respond_to do |format|
      if @adm_noticia.update(adm_noticia_params)
        format.html { redirect_to @adm_noticia, notice: t('noticias.update_success') }
        format.json { render :show, status: :ok, location: @adm_noticia }
      else
        format.html { render :edit }
        format.json { render json: @adm_noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adm/noticias/1
  # DELETE /adm/noticias/1.json
  def destroy
    @adm_noticia.destroy
    respond_to do |format|
      format.html { redirect_to adm_noticias_url, notice: t('noticias.destroy_success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adm_noticia
      @adm_noticia = Adm::Noticia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adm_noticia_params
      params.require(:adm_noticia).permit(:titulo, :subtitulo, :descricao, :imagem_capa, :autor)
    end

    def adm_noticia_upload(upload)    
      File.open(Rails.root.join('public', 'uploads', upload.original_filename), 'wb') do |file|
        file.write(upload.read)
      end
      @adm_noticia[:imagem_capa] = upload.original_filename
      
    end
  end

app/controllers/adm/videos_controller.rb
class Adm::VideosController < ApplicationController
  # before_action :require_authentication
  before_action :authenticate_user! #devise autheticação
  load_and_authorize_resource #metodo cancancan
  layout "adm_layout"
  before_action :set_adm_video, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  # GET /adm/videos
  # GET /adm/videos.json
  def index
    @adm_videos = Adm::Video.all
  end

  # GET /adm/videos/1
  # GET /adm/videos/1.json
  def show
  end

  # GET /adm/videos/new
  def new
    @adm_video = Adm::Video.new
  end

  # GET /adm/videos/1/edit
  def edit
  end

  # POST /adm/videos
  # POST /adm/videos.json
  def create
    @adm_video = Adm::Video.new(adm_video_params)

    respond_to do |format|
      #@adm_video[:codigo]=parse_youtube(params[:adm_video][:codigo])

      if @adm_video.save
        # format.html { redirect_to @adm_video, notice: t('videos.create_success') }
        # format.json { render :show, status: :created, location: @adm_video }
        flash[:notice] = t('videos.create_success')
        respond_with(@adm_video)
      else
        # format.html { render :new }
        # format.json { render json: @adm_video.errors, status: :unprocessable_entity }

        respond_with(@adm_video)

      end
    end
  end

  # PATCH/PUT /adm/videos/1
  # PATCH/PUT /adm/videos/1.json
  def update
    respond_to do |format|
      if @adm_video.update(adm_video_params)
        format.html { redirect_to @adm_video, notice: t('videos.update_success') }
        format.json { render :show, status: :ok, location: @adm_video }
      else
        format.html { render :edit }
        format.json { render json: @adm_video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adm/videos/1
  # DELETE /adm/videos/1.json
  def destroy
    @adm_video.destroy
    respond_to do |format|
      format.html { redirect_to adm_videos_url, notice: t('videos.destroy_success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adm_video
      @adm_video = Adm::Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adm_video_params
      params.require(:adm_video).permit(:titulo, :url_codigo)
    end    

  end

app/helpers/adm/banners_helper.rb
module Adm::BannersHelper
end

app/helpers/adm/dashboard_helper.rb
module Adm::DashboardHelper
end

app/helpers/adm/galerias_helper.rb
module Adm::GaleriasHelper
end

app/helpers/adm/galerias_imagens_helper.rb
module Adm::GaleriasImagensHelper
end

app/helpers/adm/noticias_helper.rb
module Adm::NoticiasHelper
end

app/helpers/adm/videos_helper.rb
module Adm::VideosHelper
end

app/views/adm/galerias_imagens/_form.html.erb
<%= form_for(@adm_galerias_imagem) do |f| %>
  <% if @adm_galerias_imagem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adm_galerias_imagem.errors.count, "error") %> prohibited this adm_galerias_imagem from being saved:</h2>

      <ul>
      <% @adm_galerias_imagem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :galeria_id %><br>
    <%= f.hidden_field :galeria_id, :value => params[:id] %>
  </div>
  <div class="form-group">
    <%= f.label :imagem %><br>
    <%= f.file_field :imagem, multiple: true %>
  </div>
  <div class="form-group">
    <%= f.submit 'Adicionar imagens', class: "btn btn-success" %>
  </div>
<% end %>

app/views/adm/galerias_imagens/edit.html.erb
<h1>Editing adm_galerias_imagem</h1>

<%= render 'form' %>

<%= link_to 'Show', @adm_galerias_imagem, class: "btn btn-info" %> |
<%= link_to 'Back', adm_galerias_imagens_path, class: "btn btn-default" %>

app/views/adm/galerias_imagens/index.html.erb
<h1>Listing adm_galerias_imagens</h1>

<%= link_to 'New Galerias imagem', new_adm_galerias_imagem_path, class: "btn btn-success" %>

<table class="table">
  <thead>
    <tr>
      <th>Galeria</th>
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adm_galerias_imagens.each do |adm_galerias_imagem| %>
    <tr>
      <td><%= adm_galerias_imagem.galeria_id %></td>
      <td><%= image_tag(adm_galerias_imagem.imagem, size: "100x100", alt: "Imagem capa")%></td>
      <td><%= link_to 'Show', adm_galerias_imagem, class: "btn btn-info" %></td>
      <td><%= link_to 'Edit', edit_adm_galerias_imagem_path(adm_galerias_imagem), class: "btn btn-primary" %></td>
      <td><%= link_to 'Destroy', adm_galerias_imagem, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Galerias imagem', new_adm_galerias_imagem_path, class: "btn btn-success" %>

app/views/adm/galerias_imagens/new.html.erb
<h1>New adm_galerias_imagem</h1>

<div id="filelist">Your browser doesn't have Flash, Silverlight or HTML5 support.</div>
<br />

<div id="container">
  <a class="btn btn-success" id="pickfiles" href="javascript:;">Selecione as imagens</a> 
  <a class="btn btn-primary" id="uploadfiles" href="javascript:;">Enviar imagens</a>
</div>

<br />
<%= link_to 'Back', adm_galerias_imagens_path, class: "btn btn-default" %>

<% content_for :js do %>
$(function(){
var uploader = new plupload.Uploader({
runtimes : 'html5,flash,silverlight,html4',
browse_button : 'pickfiles', // you can pass in id...
container: document.getElementById('container'), // ... or DOM Element itself
url : '<%= adm_galerias_imagens_path %>',
multipart: true,
   max_file_size : '10mb',
multipart_params: {
"authenticity_token" : "<%= form_authenticity_token %>",
'<%= Rails.application.config.session_options[:key] %>': '<%= request.session_options[:id] %>',
"adm_galerias_imagem[galeria_id]": '<%= params[:id] %>',
},
// Flash settings
flash_swf_url : '<%= asset_path('plupload/Moxie.swf') %>' ,
// Silverlight settings
silverlight_xap_url : '<%= asset_path('plupload/Moxie.xap') %>',

file_data_name:"adm_galerias_imagem[imagem]",
filters : {
max_file_size : '10mb',
mime_types: [
{title : "Image files", extensions : "jpg,gif,png"},
{title : "Zip files", extensions : "zip"}
]
}
});
uploader.bind('Init', function(up, params) {
$('#filelist').html("<div>Current runtime: " + params.runtime + "</div>");
});
uploader.bind('FilesAdded', function(up, files) {
$.each(files, function(i, file) {
$('#filelist').append(
'<div id="' + file.id + '">' +
'File: ' + file.name + ' (' + plupload.formatSize(file.size) + ') <strong></strong>' +'</div>'
);
});
});
uploader.bind('UploadProgress', function(up, file) {
$('#' + file.id + " b").html(file.percent + "%");
});
$('#uploadfiles').click(function(e) {
uploader.start();
e.preventDefault();
});
uploader.init();
});
<% end %> 

app/views/adm/galerias_imagens/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_adm_galerias_imagem_path(@adm_galerias_imagem), class: "btn btn-primary" %> |
<%= link_to 'Back', adm_galerias_imagens_path, class: "btn btn-default" %>

<br /><br />
<div class="row">
  <% @adm_galerias_imagem.each do |agi| %>
  <div class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
   <% if agi.imagem.blank? %>
   <a href="#" class="thumbnail">     
     <%= image_tag('noimage.png',size: "256x256", alt: "Sem imagem", title: "Sem imagem", class: "img-responsive" )%>
   </a>
   <% else %>
   <%= link_to image_tag(agi.imagem,size: "256x256", alt: "Imagem #{agi.id}", class: "img-responsive" ), '', :title => "Imagem #{agi.id}", :target => "_blank", class: "thumbnail"  %>
   <% end %>
 </div>
 <% end %>
</div>
<br />

<%= link_to 'Edit', edit_adm_galerias_imagem_path(@adm_galerias_imagem), class: "btn btn-primary" %> |
<%= link_to 'Back', adm_galerias_imagens_path, class: "btn btn-default" %>