config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'home#index'
  get 'sobre', to: 'home#sobre'
  get 'noticias', to: 'home#noticias'
  get 'noticia_view/:id', to: 'home#noticia_view'
  get 'galerias', to: 'home#galerias'
  get 'galeria_view/:id', to: 'home#galeria_view'
  get 'videos', to: 'home#videos'
  get 'contato', to: 'home#contato'
  post 'send_contato', to: 'home#send_contato'

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up'}

  namespace :adm do
    get 'dashboard', to: 'dashboard#index'
    get 'galerias/imagem_capa/:id', to: 'galerias#imagem_capa'
    resources :banners
    resources :noticias
    resources :videos
    resources :galerias
    resources :galerias_imagens
  end

  namespace :auth do
    resources :roles
  end

  root 'home#index'

end

app/views/layouts/_adm_menu.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="index.html">CMS Rails - 1.0</a>
  </div>
  <!-- Top Menu Items -->
  <ul class="nav navbar-right top-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i>
        <b class="caret"></b></a>
      <ul class="dropdown-menu message-dropdown">
        <li class="message-preview">
          <a href="#">
            <div class="media">
            <span class="pull-left">
                <img class="media-object" src="http://placehold.it/50x50" alt="">
            </span>

              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>

                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>

                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          </a>
        </li>
        <li class="message-preview">
          <a href="#">
            <div class="media">
                <span class="pull-left">
                    <img class="media-object" src="http://placehold.it/50x50" alt="">
                </span>

              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>

                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>

                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          </a>
        </li>
        <li class="message-preview">
          <a href="#">
            <div class="media">
                <span class="pull-left">
                    <img class="media-object" src="http://placehold.it/50x50" alt="">
                </span>

              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>

                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>

                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          </a>
        </li>
        <li class="message-footer">
          <a href="#">Read All New Messages</a>
        </li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
      <ul class="dropdown-menu alert-dropdown">
        <li>
          <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="#">View All</a>
        </li>
      </ul>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Admin
        <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to edit_user_registration_path, :title => t('users.profile') do %>
              <i class="fa fa-fw fa-user"></i>
              <%= t('users.profile') %>
          <% end %>
        </li>
        <li>
          <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
        </li>
        <li>
          <%= link_to '#', :title => t('sessions.settings') do %>
              <i class="fa fa-fw fa-gear"></i>
              <%= t('sessions.settings') %>
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to destroy_user_session_path, :title => t('sessions.logout'), method: "delete" do %>
              <i class="fa fa-fw fa-power-off"></i>
              <%= t('sessions.logout') %>
          <% end %>
        </li>
      </ul>
    </li>
  </ul>

  <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
      <li class="active">
        <%= link_to adm_dashboard_path, title: 'Dashboard' do %>
            <i class="fa fa-fw fa-dashboard"></i> Dashboard
        <% end %>
      </li>
      <li>
        <%= link_to adm_noticias_path, title: t('adm.menu.title.noticias') do %>
            <i class="fa fa-fw fa-newspaper-o"></i> <%= t('adm.menu.title.noticias') %>
        <% end %>
      </li>
      <li>
        <%= link_to adm_galerias_path, title: t('adm.menu.title.galerias') do %>
            <i class="fa fa-fw fa-camera"></i> <%= t('adm.menu.title.galerias') %>
        <% end %>
      </li>
      <li>
        <%= link_to adm_banners_path, title: t('adm.menu.title.banners') do %>
            <i class="fa fa-fw fa-image"></i> <%= t('adm.menu.title.banners') %>
        <% end %>
      </li>
      <li>
        <%= link_to adm_videos_path, title: t('adm.menu.title.videos') do %>
            <i class="fa fa-fw fa-video-camera"></i> <%= t('adm.menu.title.videos') %>
        <% end %>
      </li>

    </ul>
  </div>
  <!-- /.navbar-collapse -->
</nav>

app/views/layouts/_banner.html.erb
<ul class="rslides">
  <% @banners.each do |banner| %>
      <% if banner.link.blank? %>
          <li><%= image_tag(banner.imagem, size: "900x300", alt: banner.titulo) %></li>
      <% else %>
          <li><%= link_to image_tag(banner.imagem, size: "900x300", alt: banner.titulo), banner.link, :title => banner.titulo, :target => "_blank" %></li>
      <% end %>

  <% end %>
</ul>
<% content_for :js do %>
    $(function() {
        $(".rslides").responsiveSlides({
            speed: 1500,
            pause: true,
            random: true
        });
    });
<% end %> 

app/views/layouts/_menu.html.erb
<nav role="navigation" class="navbar navbar-inverse">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button data-target="#menu" data-toggle="collapse" class="navbar-toggle" type="button">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div id="menu" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', '/' %></li>
      <li><%= link_to 'Sobre', sobre_path %></li>
      <li><%= link_to 'Notícias', noticias_path %></li>
      <li><%= link_to 'Galerias', galerias_path %></li>
      <li><%= link_to 'Vídeos', videos_path %></li>
      <li><%= link_to 'Contato', contato_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/adm_layout.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Ruby on Rails, GilcierWeb">
  <meta name="author" content="GilcierWeb - gilcierweb.com.br - gilcierweb@gmail.com">
  <title>Cmsrails</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'sb-admin', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">

  <%= render 'layouts/adm_menu' %>




  <div id="page-wrapper">

    <div class="container-fluid">
      <div class="row">

        <div class="col-lg-12 col-md-12 col-sm-12">
          <header class="header-title">
            <hgroup>
              <h1>CMS Rails - 1.0</h1>
              <h4>Projeto Open Source de GilcierWeb</h4>
            </hgroup>

          </header>

          <section>
            <%= yield %>
          </section>

          <footer class="text-center">
            <p>
              Copyright &copy; GilcierWeb Rails - <%= Time.new.year %> -
              <a href="http://gilcierweb.com.br" target="_blank" title="gilcierweb.com.br">gilcierweb.com.br</a>

            <p>
          </footer>
        </div>
      </div>
      <!-- /.row -->

    </div>
    <!-- /.container-fluid -->

  </div>
  <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->
<!--Scripts-->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<% if content_for?(:js) %>
    <script type="text/javascript">
        <%= yield :js %>
    </script>
<% end %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Ruby on Rails, GilcierWeb">
  <meta name="author" content="GilcierWeb - gilcierweb.com.br - gilcierweb@gmail.com">
  <title>Cmsrails</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">

    <header class="header-title">
      <div class="col-lg-9 col-md-9 col-sm-9">
        <hgroup>
          <h1>CMS Rails - 1.0</h1>
          <h4>Projeto Open Source de GilcierWeb</h4>
        </hgroup>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-3">

        <ul class="header-login">
          <% if user_signed_in? %>
              <li>
                <%= link_to(destroy_user_session_path, method: :delete, class: 'btn btn-default') do %>
                    <i class="glyphicon glyphicon-lock"></i><%= t('sessions.logout') %>
                <% end %>
              </li>
          <% else %>
              <li><%= link_to "Log in", new_user_session_path, class: 'btn btn-success' %></li>
          <% end %>
        </ul>
      </div>
    </header>

    <div class="col-lg-12 col-md-12 col-sm-12">
      <section>
        <%= render 'layouts/menu' %>

        <% flash.each do |key, value| %>
            <div class="<%= flash_class(key) %> fade in">
              <a href="#" class="close" data-dismiss="alert">&times;</a>
              <%= value %>
            </div>
        <% end %>

        <% if (current_page?('/')) %>
            <%= render 'layouts/banner' %>
        <% end %>
      </section>

      <section>

        <%= yield %>

      </section>

      <footer class="text-center">
        <hr/>
        <p>
          Copyright &copy; GilcierWeb Rails - <%= Time.new.year %> -
          <a href="http://gilcierweb.com.br" target="_blank">gilcierweb.com.br</a>

        <p>
      </footer>
    </div>
  </div>
</div>
<!--Scripts-->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<% if (params[:action] == 'galeria_view') || (params[:action] == 'videos') %>
    <%= javascript_include_tag 'jquery.colorbox-min', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'i18n/jquery.colorbox-pt-BR', 'data-turbolinks-track' => true %>
<% end %>

<% if content_for?(:javascript_includes) %>
    <%= yield :javascript_includes %>
<% end %>

<% if content_for?(:js) %>
    <script type="text/javascript">
        <%= yield :js %>
    </script>
<% end %>

</body>
</html>

app/views/layouts/auth_layout.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Ruby on Rails, GilcierWeb">
  <meta name="author" content="GilcierWeb - gilcierweb.com.br - gilcierweb@gmail.com">
  <title>Cmsrails</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <header class="header-title">
        <hgroup>
          <h1>CMS Rails - 1.0</h1>
          <h4>Projeto Open Source de GilcierWeb</h4>
        </hgroup>

      </header>

      <section>

        <% flash.each do |key, value| %>
            <div class="<%= flash_class(key) %> fade in">
              <a href="#" class="close" data-dismiss="alert">&times;</a>
              <%= value %>
            </div>
        <% end %>

        <%= yield %>

      </section>

      <footer class="text-center">
        <hr/>
        <p>
          Copyright &copy; GilcierWeb Rails - <%= Time.new.year %> -
          <a href="http://gilcierweb.com.br" target="_blank">gilcierweb.com.br</a>
        <p>
      </footer>
    </div>
  </div>
</div>
<!--Scripts-->
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<% if (params[:action] == 'galeria_view') || (params[:action] == 'videos') %>
    <%= javascript_include_tag '/assets/i18n/jquery.colorbox-pt-BR', 'data-turbolinks-track' => true %>
<% end %>
<% if content_for?(:js) %>
    <script type="text/javascript">
        <%= yield :js %>
    </script>
<% end %>
</body>
</html>